#%RAML 1.0 NamedExample

value:
  -
    id: 1
    firstName: JAYGANESH
    lastName: B
    address: XXX
    postal: 605001
    country: AUSTRALIA
    miles: 1000
    creationDate: 2016-02-28T16:41:41.090Z
    type: loan